### ISSUE TITLE
banking management system in c

### ISSUE THREAD

**Issue by sidhrth04** [MrAnonymous09/hacktoberfest-solutions-submissions#2]
@MrAnonymous09, Please assign me this issue 
i will get you a menu driven banking management system using c
it will be a great help
thank you.

**Comment by 0xali3n** [comment]
Ya you can contribute in the respective folder.

**Comment by sidhrth04** [comment]
can you assign me the issue

**Comment by 0xali3n** [comment]
CAn you just add the file in the specified folder!

**Comment by 0xali3n** [comment]
Thanku @sidhrth04
